//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ApplicationCore.Properties.ResourcesVN", typeof(ResourcesVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string AddComplete {
            get {
                return ResourceManager.GetString("AddComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu trống.
        /// </summary>
        public static string DataEmpty {
            get {
                return ResourceManager.GetString("DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại.
        /// </summary>
        public static string DataNotExist {
            get {
                return ResourceManager.GetString("DataNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeleteComplete {
            get {
                return ResourceManager.GetString("DeleteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} đã có trong hệ thống.
        /// </summary>
        public static string ErrorDevMsgDuplicate {
            get {
                return ResourceManager.GetString("ErrorDevMsgDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không được để chống.
        /// </summary>
        public static string ErrorDevMsgRequire {
            get {
                return ResourceManager.GetString("ErrorDevMsgRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu {0} không hợp lệ!.
        /// </summary>
        public static string ErrorDevMsgValidate {
            get {
                return ResourceManager.GetString("ErrorDevMsgValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! Vui lòng liên hệ với MISA!.
        /// </summary>
        public static string ErrorUserMsgExeption {
            get {
                return ResourceManager.GetString("ErrorUserMsgExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tệp nhập khẩu.
        /// </summary>
        public static string ErrorUserMsgNullFile {
            get {
                return ResourceManager.GetString("ErrorUserMsgNullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập trường bắt buộc  {0}.
        /// </summary>
        public static string ErrorUserMsgRequire {
            get {
                return ResourceManager.GetString("ErrorUserMsgRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu {0} không hợp lệ vui lòng kiểm tra lại!.
        /// </summary>
        public static string ErrorUserMsgValidate {
            get {
                return ResourceManager.GetString("ErrorUserMsgValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu hợp lệ.
        /// </summary>
        public static string MsgIsValid {
            get {
                return ResourceManager.GetString("MsgIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string MsgNoValid {
            get {
                return ResourceManager.GetString("MsgNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu lệnh chạy thành công nhưng không thêm được vào trong CSDL! Vui lòng kiểm tra lại câu lệnh Insert.
        /// </summary>
        public static string NoAddInDataBase {
            get {
                return ResourceManager.GetString("NoAddInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không xóa được dữ liệu ! Vui lòng kiểm tra lại câu lệnh Delete hoặc dữ liệu gửi lên.
        /// </summary>
        public static string NoDeleteInDataBase {
            get {
                return ResourceManager.GetString("NoDeleteInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu lệnh chạy thành công nhưng không cập nhật được vào trong CSDL! Vui lòng kiểm tra lại câu lệnh Update.
        /// </summary>
        public static string NoUpdateInDataBase {
            get {
                return ResourceManager.GetString("NoUpdateInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null File.
        /// </summary>
        public static string NullFile {
            get {
                return ResourceManager.GetString("NullFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thành công.
        /// </summary>
        public static string UpdateComplete {
            get {
                return ResourceManager.GetString("UpdateComplete", resourceCulture);
            }
        }
    }
}
